### ISSUE TITLE
[BUG] I can't get tasks for all

### ISSUE THREAD

**Issue by usFox** [onfleet/pyonfleet#31]
I try to get all tasks
`tasks = on_api.tasks.get(queryParams={"from":1455072025000,"state":0})`
Error is 
`  File "/home/webadm/dirct.us/phalapi/Python/NewTools/Tools_onfleet.py", line 811, in <module>
    API.check_task()
  File "/home/webadm/dirct.us/phalapi/Python/NewTools/Tools_onfleet.py", line 758, in check_task
    tasks = on_api.tasks.get(queryParams={"from":1455072025000,"state":0})
  File "/usr/local/python/3.8/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/python/3.8/lib/python3.8/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
  File "/usr/local/python/3.8/lib/python3.8/site-packages/onfleet/request.py", line 69, in __call__
    raise ValidationError(*exception_args)
onfleet.error.ValidationError: ('The values of one or more parameters are invalid.', 1000, '1d6f8d4a-cca7-4106-b658-4b470d945255', 'From time was not provided or contains an invalid value')`

**Comment by jamesliupenn** [comment]
@usFox I just checked and it seems that we are expecting a string and not a dictionary in `queryParams` (See https://github.com/onfleet/pyonfleet/blob/master/onfleet/request.py#L119). This is likely a mistake since we should be supporting dictionaries and multiple query parameters. I will issue a fix soon.

As a workaround for now, you can do something like `tasks = on_api.tasks.get(queryParams="from=1455072025000")` to get some results.

**Comment by jamesliupenn** [comment]
Filing a bug for Onfleet's team for prioritization 👍

**Comment by jamesliupenn** [comment]
@usFox this is fixed in v1.2.1 release in PR#33

**Comment by ruchika-chaudhari** [comment]
@jamesliupenn 
I am trying to get all the tasks from a date.. this is what I have been trying: 
tasks = onfleet_api.tasks.get(queryParams="timeCreated:1455072025000")
tasks = onfleet_api.tasks.get(queryParams="from=1638729079000")
tasks = onfleet_api.tasks.get(timeCreated = '1638729079000')

Still throwing me error: OnfleetException: 1900: One or more parameters required for this request are either missing or have an invalid format. ()

Nothing seems to work. Please suggest some way to access this.

**Comment by jamesliupenn** [comment]
@ruchika-chaudhari 

For your 1st request: Please refer back to [Onfleet's API documentation](https://docs.onfleet.com/reference#list-tasks), `timeCreated` is not a valid query parameter

For your 2nd request: This request looks good to me, I got a response from this request. You can also do `onfleet_api.tasks.get(queryParams={"from" : 1638729079000})` which is equivalent to your 2nd request.

For your 3rd request: Please refer to the API doc as the 1st one, also `queryParams` is needed if you are passing in a query parameter

**Comment by ruchika-chaudhari** [comment]
Thank You for your response!!

![image](https://user-images.githubusercontent.com/95772773/145331307-64fdd520-95e3-477b-ae90-bd0e25971cfc.png)
 
But still got this

**Comment by ruchika-chaudhari** [comment]
I think this is about what I am putting in front of 'from'. Any documentation on the date value? what values it takes?

**Comment by ruchika-chaudhari** [comment]
Thank You for your response!

**Comment by ruchika-chaudhari** [comment]
I am doing request as **onfleet_api.tasks.get(queryParams={"from" : 1655877600000, "to" : 1655963999999})**   Even if I change the from and to timestamps, all I get is 64 rows exacly.. be it one month duration or one day. What could be the issue?
